### AUTOGENERATED; DO NOT EDIT ###
# -*- Makefile -*- 
.POSIX:
CDEFS=
COPT=-std=gnu99 -O3 -g -fstrict-aliasing
CWARN=-Wall -W -Wstrict-prototypes -Wmissing-prototypes
CINC=

CDBG=
CFLAGS=$(COPT) $(CWARN) $(CDBG) $(CDEFS) $(CINC) $(XCF)

OO=orbit.o orbio.o
PO=test_rdwr.o sim.o disas.o ideco.o icomp.o
OBJS=$(PO) $(OO)

all: sim disas icomp ideco

icomp: icomp.o $(OO)
	$(CC) $(CFLAGS) $(LFLAGS) $(OO) icomp.o -o icomp -lm

ideco: ideco.o $(OO)
	$(CC) $(CFLAGS) $(LFLAGS) $(OO) ideco.o -o ideco -lm

disas: disas.o $(OO)
	$(CC) $(CFLAGS) $(LFLAGS) $(OO) disas.o -o disas -lm

test_rdwr: test_rdwr.o $(OO)
	$(CC) $(CFLAGS) $(LFLAGS) $(OO) test_rdwr.o -o test_rdwr -lm

sim: sim.o $(OO)
	$(CC) $(CFLAGS) $(LFLAGS) $(OO) sim.o -o sim -lm

clean:
	-rm -f $(OBJS) $(PO:.o=)

CS=$(OBJS:.o=.c)
Makefile: Makefile.tmpl $(CS)
	@echo '### AUTOGENERATED; DO NOT EDIT ###' > $@
	cat Makefile.tmpl >> $@
	$(MAKE) -f Makefile.tmpl _depend
_depend:
	@gcc -MM $(CDEFS) $(CINC) $(CS) >> Makefile
###END###
test_rdwr.o: test_rdwr.c orbio.h orbit.h
sim.o: sim.c orbio.h orbit.h
disas.o: disas.c orbio.h orbit.h
ideco.o: ideco.c orbio.h orbit.h
icomp.o: icomp.c orbio.h orbit.h
orbit.o: orbit.c orbio.h orbit.h
orbio.o: orbio.c orbio.h orbit.h
