### AUTOGENERATED; DO NOT EDIT ###
# -*- Makefile -*- 
.POSIX:
CDEFS=
COPT=-std=gnu99 -O3 -g -fstrict-aliasing
CWARN=-Wall -W -Wstrict-prototypes -Wmissing-prototypes
CINC=

CDBG=
CFLAGS=$(COPT) $(CWARN) $(CDBG) $(CDEFS) $(CINC) $(XCF)

OO=orbit.o orbio.o
OBJS=test_rdwr.o $(OO)

all: $(OBJS)

test_rdwr: test_rdwr.o $(OO)
	$(CC) $(CFLAGS) $(LFLAGS) $(OO) test_rdwr.o -o test_rdwr

clean:
	-rm -f $(OBJS)

CS=$(OBJS:.o=.c)
Makefile: Makefile.tmpl $(CS)
	@echo '### AUTOGENERATED; DO NOT EDIT ###' > $@
	cat Makefile.tmpl >> $@
	$(MAKE) -f Makefile.tmpl _depend
_depend:
	@gcc -MM $(CDEFS) $(CINC) $(CS) >> Makefile
###END###
test_rdwr.o: test_rdwr.c orbio.h orbit.h
orbit.o: orbit.c orbit.h
orbio.o: orbio.c orbio.h orbit.h
